# Generated by Django 3.2.19 on 2023-06-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
