# Generated by Django 3.2.19 on 2023-06-29 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0002_rename_image_image_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['ctry_title'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
