# Generated by Django 3.2.19 on 2023-07-08 13:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0003_auto_20230629_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='ctry_title',
            field=models.CharField(max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alttext',
            field=models.CharField(max_length=50, verbose_name='Alternative Text'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=80, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Image'),
        ),
    ]
